language: python
dist: xenial

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "nightly"
  - "pypy"
  - "pypy3.5"

env:
  - PRE_COMMIT_CMD=""

matrix:
  include:
    - name: "pre-commit"
      python: "3.7"
      env:
        - PRE_COMMIT_CMD="pre-commit run --all-files"
  allow_failures:
    - python: "3.8-dev"
    - python: "nightly"

install:
  - pip install tox-travis codecov pre_commit

script:
 - tox
 - $PRE_COMMIT_CMD

after_success:
 - codecov
 - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then bumpversion --verbose minor && bash push.sh; fi

cache: pip

# deploy:
#   provider: pypi
#   user: $PYPI_USERNAME
#   password: $PYPI_PASSWORD
#   on:
#     branch: master
#     tags: false
